"""
Suggested replies service — generates 2-4 contextual quick-reply buttons.

These appear below the agent's response as clickable pills. When the user
taps one, it sends that text as their next message. The goal is to eliminate
the "blank input" problem and guide the conversation toward the most valuable
next step for the patient.

Design principles:
  - Written in the user's voice ("I have a note to upload", not "Upload your note")
  - Specific to this conversation moment — not generic
  - Always include at least one "different direction" option so the user isn't trapped
  - Short (≤ 60 characters) — they're buttons, not sentences
  - Generated by GPT-4o at low temperature for reliability
  - Non-blocking: if the call fails, return [] and the UI just shows a text input

The suggestions are ephemeral UI hints — they are NOT persisted to the database.
"""

from openai import AsyncOpenAI
from pydantic import BaseModel, Field

from config import get_settings

settings = get_settings()


SUGGESTIONS_SYSTEM = """
You are generating quick-reply buttons for a patient health chat app.
Your job: given the assistant's last response and the conversation context,
generate 2-4 short suggested replies the USER might want to send next.

RULES:
1. Write each suggestion in the USER's voice: "I have a note to upload", "Tell me more about..."
2. Make them SPECIFIC to this exact moment in the conversation — not generic
3. Keep each suggestion SHORT: maximum 60 characters
4. Include a variety: some action-oriented ("I have a document to share"), some
   question-oriented ("What does that mean for me?"), one "different path" option
5. Do NOT repeat what the user just said
6. Do NOT ask questions — these are statements/actions the user would send
7. Maximum 4 suggestions, minimum 2

CONTEXT-SPECIFIC GUIDANCE:

After a refusal (agent said it can't give medical advice):
  → "I have a note from my doctor to share"
  → "Tell me what my records say"
  → "Help me write a question for my care team"

After offering an upload:
  → "I'll upload a photo of the note now"
  → "Let me describe what the doctor told me instead"
  → "I don't have the note yet"

After explaining a note:
  → "Can you explain [specific term from the note] more?"
  → "What questions should I ask at my next visit?"
  → "I have more paperwork to share"
  → "What about my medications?"

After emotional support / care navigation:
  → "I have a note from today's visit"
  → "I have questions about what happens next"
  → "Can you help me prepare for my follow-up?"
  → "I'd like to know what my records say"

After scheduling or appointment discussion:
  → "What should I ask at that appointment?"
  → "Can you remind me what was discussed last time?"

Return ONLY a JSON array of strings. No explanation.
Example: ["I have a note to upload", "Tell me what my records say", "Help me write a question for my care team"]
"""


class SuggestionsResult(BaseModel):
    suggestions: list[str] = Field(max_length=4)


async def generate_suggested_replies(
    response_text: str,
    user_message: str,
    intent: str | None,
    care_stage: str = "unknown",
    has_records: bool = False,
    action_cards: list | None = None,
) -> list[str]:
    """
    Generate 2-4 contextual quick-reply suggestions for the user.
    Returns [] on any failure — the UI falls back to free-text input gracefully.
    """
    if not settings.openai_configured:
        return _fallback_suggestions(intent)

    try:
        client = AsyncOpenAI(api_key=settings.openai_api_key)

        context_parts = [
            f"User's message: {user_message[:200]}",
            f"Intent classified as: {intent or 'unknown'}",
            f"Care stage: {care_stage}",
            f"Patient has records in the system: {has_records}",
        ]
        if action_cards:
            card_labels = [c.get("label", "") for c in action_cards if c.get("label")]
            if card_labels:
                context_parts.append(f"Action cards shown: {', '.join(card_labels)}")

        context_parts.append(f"\nAssistant's response:\n{response_text[:500]}")
        context = "\n".join(context_parts)

        result = await client.chat.completions.create(
            model=settings.openai_model,
            messages=[
                {"role": "system", "content": SUGGESTIONS_SYSTEM},
                {"role": "user", "content": context},
            ],
            temperature=0.4,
            max_tokens=150,
            response_format={"type": "json_object"},
        )

        import json
        raw = result.choices[0].message.content or ""
        parsed = json.loads(raw)

        # Accept either {"suggestions": [...]} or a bare array
        if isinstance(parsed, list):
            suggestions = parsed
        elif isinstance(parsed, dict):
            suggestions = parsed.get("suggestions", [])
        else:
            return _fallback_suggestions(intent)

        # Enforce limits and clean
        suggestions = [str(s).strip() for s in suggestions if str(s).strip()][:4]
        suggestions = [s for s in suggestions if len(s) <= 80]

        return suggestions if len(suggestions) >= 2 else _fallback_suggestions(intent)

    except Exception:
        return _fallback_suggestions(intent)


def _fallback_suggestions(intent: str | None) -> list[str]:
    """Return static fallback suggestions when the API call fails."""
    if intent == "MEDICAL_ADVICE":
        return [
            "I have a note from my doctor to share",
            "Tell me what my records say",
            "Help me write a question for my care team",
        ]
    if intent in ("NOTE_EXPLANATION", "RECORD_LOOKUP"):
        return [
            "Can you explain that in simpler terms?",
            "What should I ask at my next visit?",
            "I have more paperwork to share",
        ]
    if intent == "CARE_NAVIGATION":
        return [
            "I have a note from today's visit",
            "I have questions about what happens next",
            "Can you look at my recent records?",
        ]
    # Generic fallback
    return [
        "I have a document to share",
        "What do my records say?",
        "Help me prepare for my next visit",
    ]
